---
- name: Creating VPC
  ec2_vpc_net:
          name: "{{vpc_name}}"
          region: "{{region}}"
          state: present
          cidr_block: "{{cidr_block}}"
          resource_tags: { "Environment":"{{tag_env}}" }
  register: vpc
  vars:
    ansible_python_interpreter: python